[package]
name = "linear_algebra_in_rust"
version = "0.1.0"
authors = ["Ludwig Granstedt <ludwiggranstedt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
num-traits = "0.2.14"